POST http://nopepsi:0608@localhost:5572/operations/stat
Content-Type: application/json

{
  "fs": "/",
  "remote": "/home/nopepsi-lenovo-laptop/SyncDuoServer/src/test/resources/contentParentFolder/",
  "opt": {
    "dirsOnly": true
  }
}

###

POST http://nopepsi:0608@localhost:5572/operations/copyfile
Content-Type: application/json

{
  "srcFs": "/",
  "srcRemote": "/home/nopepsi-dev/IdeaProject/SyncDuoServer/src/test/resources/sourceFolder/TestFile0_3.bin",
  "dstFs": "/",
  "dstRemote": "/home/nopepsi-dev/IdeaProject/SyncDuoServer/src/test/resources/contentParentFolder/random1/justBinary.bin"
}

###

POST http://nopepsi:0608@192.168.28.199:5572/operations/check
Content-Type: application/json

{
  "srcFs": "/home/nopepsi-laptop/SyncDuoApp/Resilio-Sync/sync/nopepsi-desktop/Warehouse",
  "dstFs": "/home/nopepsi-laptop/SyncDuoApp/contentPath/Image-Warehouse",
  "oneway": true,
  "_config":{
    "SizeOnly": true,
    "Checkers": 1
  },
  "_async": true
}